version: '3.4'

services:
  webapp:
    build: .
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=db;Database=TuBaseDeDatos;User Id=sa;Password=StrongPass1!;Trusted_Connection=False;MultipleActiveResultSets=true;
      - ASPNETCORE_URLS=http://+:5000
    depends_on:
      - db

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "StrongPass1!"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql

volumes:
  sql_data: